project:
  type: website
  output-dir: docs
website:
  title: "Stats 101A Spring 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - RRefresher.qmd

format:
  html:
    page-layout: full
    theme: cosmo
    css: styles.css
    toc: true

# Set default options for every bookpage that may or may not include webR.
webr: 
  show-startup-message: false    # Disable displaying status of webR initialization
  packages: ['ggplot2', 'dplyr', 'readr', 'tidyr', 'alr4'] # Install R packages on document open

# Attach webR extension for the project
filters:
  - webr

resources: 
  - "webr-serviceworker.js"
  - "webr-worker.js"

